### ISSUE TITLE
No support for unregistration

### ISSUE THREAD

**Issue by matiwinnetou** [matiwinnetou/cardano-oracle-publisher#1]
Currently we register oracles here by submitting value on key 1967:
```
https://bi.stakepoolcentral.com/tx_metadatakeylist?epoch_no=228&key=1967
```

Issues:

1. There is already one pool, which stopped sending transactions
2. People may want to change a hash because name of stakepool changes or something

What about a solution where one specifies: "oracle_publisher", which can be either ACTIVE or INACTIVE.

```
{
  "1967": {
    "oracle_publisher": "ACTIVE",
    "metadata": "https://cardano.fans/mypool.metadata.json",
    "hash": "5f1cbafbb46d8c8c92fae15e96170dbe6fba51cd66cda826d684bca3b0fad1bc"
  }
}
```

One could then send transaction to deactivate an oracle_publisher?

**Comment by mmahut** [comment]
There is no unregistration by design, as it would add complexity and doesn't provide additional value. Most importantly there is no way to build incentives for people to actually deregister their oracles.

> There is already one pool, which stopped sending transactions

I'm not sure I understand. Do you mean if the address keys are compromised/lost? If so, it is same as with stake pools, the host should scrap the hosted metadata file and rebuild a new oracle.

> People may want to change a hash because name of stakepool changes or something

As this is based on blockchain, changing the metadata for the same `address` should be done by resubmitting the registration, same as with for example as we do with the stake pool certificates, where the latest on chain, is the valid one.

**Comment by matiwinnetou** [comment]
thanks, makes sense
